### ISSUE TITLE
Possibly Not grabbing all Lineups for a Zip code

### ISSUE THREAD

**Issue by bonelifer** [bluezed/repository.bluezed#2]
I'm in the US, and it doesn't seem to grab all the lineups for my zip code: 71901. It should have USA-AR03460-QAM as an option and it should also have USA-AR03460-X. Instead I'm only seeing the lineups for various Satellites.  I've tested and tv_grab_sd_json see's that lineup. The tv_grab_zz_sdjson_sqlite grabber also see's them.

**Comment by bluezed** [comment]
The guide is currently showing only the "pretty name" rather than the lineup code.
The lineup code "USA-AR03460-QAM" is shown as "Resort TV Cable Co Inc - QAM" and "USA-AR03460-X" would be "Resort TV Cable Co Inc - Digital".

Hope that helps...

**Comment by bonelifer** [comment]
I know their "pretty names"(Long time SchedulesDirect user), if it had shown those I wouldn't of posted.  Screenshots show all for 71901. Running OSMC (Kodi 16.1)

https://s19.postimg.org/hkonfs25v/screenshot002.png
https://s19.postimg.org/na4w038c3/screenshot003.png

**Comment by bonelifer** [comment]
Ok, after having the login problem, I started jumping to conclusions when I didn't see my lineups.  So I didn't bother trying the edit lineups button. Since I already have the lineups added via another grabber, they were already "added". This one can be closed.
